run:
  timeout: 5m

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/tlipoca9/yevna)
      - blank
      - dot
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: github.com/tlipoca9/yevna
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#add-constant
      - name: add-constant
        severity: warning
        disabled: false
        exclude: [""]
        arguments:
          - maxLitCount: "3"
            allowStrs: '""'
            allowInts: "0,1,2,0644"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#cyclomatic
      - name: cyclomatic
        severity: warning
        disabled: false
        exclude: [""]
        arguments: [50]
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#line-length-limit
      - name: line-length-limit
        severity: warning
        disabled: true
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#cognitive-complexity
      - name: cognitive-complexity
        severity: warning
        disabled: false
        exclude: [""]
        arguments: [50]
      - name: unhandled-error
        severity: warning
        disabled: false
        arguments:
         - "bytes.Buffer.WriteString"
         - "fmt.Printf"
         - "fmt.Println"
      - name: dot-imports
        severity: warning
        disabled: false
        exclude: []
        arguments:
          allowedPackages: ["github.com/onsi/ginkgo/v2","github.com/onsi/gomega"]

linters:
  enable:
    - asasalint
    - errcheck
    - gci
    - gofmt
    - goimports
    - gosimple
    - gosec
    - govet
    - revive
    - sloglint
    - staticcheck
    - stylecheck
    - tagalign
    - usestdlibvars
    - unconvert
