run:
  timeout: 5m

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/tlipoca9/yevna)
      - blank
      - dot
  gocognit:
    min-complexity: 50
  gocyclo:
    min-complexity: 50
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: github.com/tlipoca9/yevna

linters:
  enable:
    - asasalint
    - errcheck
    - gci
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - gosec
    - govet
    - revive
    - sloglint
    - staticcheck
    - stylecheck
    - tagalign
    - usestdlibvars
    - unconvert
    - unused
